all: zip

zip:
	zip 0816153.zip Makefile Fildes/solve.py cyclicRNG/solve.py Teleportation/*solve* Timeout/solve.sh Timeout/test.gdb Timeout/inject.c Timeout/Makefile Secret/solve.py

clean:
	rm -f 0816153.zip
